---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    author: intelliqit
    name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres
    spec:
      containers:
        - name: mypostgres
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: intelliqit
            - name: POSTGRES_USER
              value: myuser
            - name: POSTGRES_DB
              value: mydb
...
