---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app
  labels:
    author: intelliqit
    name: worker-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker-app
  template:
    metadata:
      name: worker-app-pod
      labels:
        name: worker-app
    spec:
      containers:
        - name: my-worker
          image: dockersamples/examplevotingapp_worker
...
